### ISSUE TITLE
Add hint about writeable paths to intro

### ISSUE THREAD

**Issue by lfuelling** [lfuelling/lrkFM#105]
As seen in #69, it would be nice to have a hint about the writeable olders in the intro.

Currently it's known that `/storage/emulated/0/Downloads` is not writeable but `../Documents` is (at least on the emulator)

**Comment by soredake** [comment]
In my case it cannot read or write to any directory.

**Comment by lfuelling** [comment]
Hmm, do you know how your storage is organized? 
Does your phone have an sd card? In that case, only `/storage/sd` (or `/sdcard` or something similar) should be writeable.

I'm really sorry about all this trouble by the way. 🙈

**Comment by soredake** [comment]
No sdcard is present, this may help:
https://github.com/Catfriend1/syncthing-android/pull/459
https://github.com/Catfriend1/syncthing-android/pull/618

**Comment by lfuelling** [comment]
The first link is unfortunately only valid for apps targeting Android < 11 ([Android Docs](https://developer.android.com/training/data-storage/use-cases#:~:text=After%20you%20update%20your%20app%20to%20target%20Android%2011))

I'll give the strategy of the second link a try, would you be willing to join [the beta](https://play.google.com/apps/testing/io.lerk.lrkFM) to see if it works for you?
(If you do please ignore the feedback link if it is not showing GitHub)

**Comment by soredake** [comment]
Joined beta and installed app, waiting for app update.

**Comment by lfuelling** [comment]
I haven't published anything yet 🙈 

Also a great note in [another docs page](https://support.google.com/googleplay/android-developer/answer/9956427?hl=en):
> Due to COVID-19 related considerations, apps that target Android 11 (API level 30) and request All files access cannot be uploaded to Google Play until early 2021. This includes new apps as well as updates to existing apps. This temporary uploading restriction only affects apps that both target Android 11 (API level 30) and request the All files access permission.

Great. So they break the API but delay the workaround due to COVID 🤦

**Comment by lfuelling** [comment]
Okay, not even beta uploads work. I get an error in the Dev Console. 🤦 

If you still want to see if it works please use the APK directly: https://stuff.lrk.sh/lrkFM-v2.5.0b1.apk

**Comment by soredake** [comment]
No change, maybe logcat (only lrk logs) will help
[logcat_11-09-2020_19-59-13.txt](https://github.com/lfuelling/lrkFM/files/5512429/logcat_11-09-2020_19-59-13.txt)

**Comment by lfuelling** [comment]
Okay, so considering the following lines:

```
[11-09 19:58:27.675 19488:19488 D/io.lerk.lrkFM.activities.file.FileActivity] Extracting from uri: 'content://me.zhanghai.android.files.file_provider/file%253A%252F%252F%252Fstorage%252Femulated%252F0%252FDownload%252Fsecret.7z'...
[11-09 19:58:27.688 3768:4654 E/InputDispatcher] Window handle Window{6931b2 u0 io.lerk.lrkFM/io.lerk.lrkFM.activities.file.FileActivity} has no registered input channel
--> [11-09 19:58:27.695 19488:19488 D/io.lerk.lrkFM.UriUtil] Temp file created: '/data/user/0/io.lerk.lrkFM/cache/secret4626393681241621260.7z'!
--> [11-09 19:58:27.723 19488:19488 D/io.lerk.lrkFM.UriUtil] File written 'successfully'!
--> [11-09 19:58:27.759 19488:23448 E/io.lerk.lrkFM.tasks.archive.ArchiveUtil] Error extracting 7z
--> [11-09 19:58:27.837 19488:24368 W/io.lerk.lrkFM.tasks.DirectoryLoaderTask] Can't read '/storage/emulated': Permission denied!
[11-09 19:58:27.851 19488:24368 W/io.lerk.lrkFM.tasks.DirectoryLoaderTask] Can't read '/storage/emulated': Permission denied!
```

It looks like the archive was read successfully but there was an error while writing the extracted files. 
Additionally (from the screencaps) it looks like you tried to extract the archive in the "current folder" (by selecting "no" in the path input dialog) which seems to be `/storage/emulated`.
Try navigating to a writable directory first, then extracting the archive. Or select "yes" in the dialog and enter a writable path. 
I found that on API 29 (Android 10) `/sdcard` is a link (to `/mnt/sdcard`) which is writable even if there is no sd "inserted" into the emulator. Downloads are apparently also stored there.

**Comment by soredake** [comment]
Unfortunately i get permission denied with every folder, tried /sdcard, /storage/emulated/0, /data/user/0

**Comment by soredake** [comment]
Another file managers sets [requestLegacyExternalStorage](https://github.com/zhanghai/MaterialFiles/blob/master/app/src/main/AndroidManifest.xml#L30), seems that is the only way to fix filesystem access on android 10.

**Comment by lfuelling** [comment]
Yes. Unfortunately that doesn't work for apps targeting API >= 30, which the current release is using.
I created another [test release](https://github.com/lfuelling/lrkFM/releases/tag/v2.5.0b2) which is using API 29, this should also appear in the GooglePlay Beta track in a few hours.

**Comment by soredake** [comment]
It works now! Can you also make /storage/emulated/0 default path?

**Comment by lfuelling** [comment]
Great! 
You can set the home directory in the App settings :)
