### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by trymeouteh** [lfuelling/lrkFM#118]
Please get the app on the main F-Droid repo.

**Comment by lfuelling** [comment]
Hi, that will be not possible because the app is using Android SDK versions that will be rejected by the F-Droid team.
The only way of installing using F-Droid is using [this repository](https://apt.izzysoft.de/fdroid/index/apk/io.lerk.lrkFM).

**Comment by trymeouteh** [comment]
Is this app fully open source? Why would they reject the Android SDK version that is used?

**Comment by lfuelling** [comment]
Because the sources of the SDK are not published and [that's against their policies](https://gitlab.com/fdroid/rfp/-/issues/755#note_111293928).
