### ISSUE TITLE
Design Material

### ISSUE THREAD

**Issue by mendezand** [lfuelling/lrkFM#12]
Hi.
I'm an amateur graphic designer. I can help you in the design part of the application. I can start by making a new logo for the application. Anything do not hesitate to ask me.

Greetings.

**Comment by lfuelling** [comment]
Hi,

feel free to submit a pull request :)

**Comment by mendezand** [comment]
I can do a test on [Adapticon](https://adapticon.tooo.io) and sent you a sample. You can ask me for any modification if you wish.

**Comment by lfuelling** [comment]
That would be nice. I didn't know the site before. 

The only thing I would change is matching the pivot of the looking glass with the pivot of the folder.

**Comment by mendezand** [comment]
What do you mean, pivot? 😊

**Comment by lfuelling** [comment]
The inclination. The top of the folder is nearer to the user than the bottom. The same should apply to the looking glass. :)

**Comment by mendezand** [comment]
This is a preview of how it would look like an adaptive icon.

PS: That background is a test.
![image](https://user-images.githubusercontent.com/38763253/40214711-4af68ffc-5a2a-11e8-830c-d61faab946a8.png)

**Comment by lfuelling** [comment]
I like the structure of the background! (and the icon itself)
Could you use the background color of the current application icon? I wonder if it fits in the current color scheme.

**Comment by mendezand** [comment]
![image](https://user-images.githubusercontent.com/38763253/40264550-4b00e446-5af4-11e8-91e3-3bafdf540326.png) ![image](https://user-images.githubusercontent.com/38763253/40264551-56f69a8e-5af4-11e8-834b-e66eb305eb6c.png) ![image](https://user-images.githubusercontent.com/38763253/40264552-5ff17d20-5af4-11e8-950c-c6a83fcedb8a.png)

What do you think? If you approve my design I proceed to send you all the editable files and create the pull request.

**Comment by lfuelling** [comment]
I think it's great :)

**Comment by mendezand** [comment]
I attached the link to the editable files, SVG and icon in PNG.
[Download link](https://drive.google.com/file/d/1NMKbuSHPnqV9DJ-7cN5AzOqDRTxTZfub/view?usp=sharing)

**Comment by lfuelling** [comment]
#21 is merged.

**Comment by mendezand** [comment]
If you need help in another application you can contact by email.
