### ISSUE TITLE
Can't share files through whatsapp

### ISSUE THREAD

**Issue by crysports** [lfuelling/lrkFM#19]
#### Expected behaviour

We should be able to share files through whatsapp .

#### Actual behaviour

I long pressed on a file and found many options and then I clicked on share option to share the file.
I tried to share the file through whatsapp but the operation failed and a pop up message was displayed saying 'try again'.

##### How to reproduce

- Download the app from this [link](https://play.google.com/store/apps/details?id=io.lerk.lrkFM&utm_source=repo_link&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1)

- Grant all permissions and be sure to turn off screen overlay
- Long press on a file to select it 
- Try to share the file through whatsapp
- You will encounter the bug.

#### Recording of the bug

![20180519_171529.gif](https://steemitimages.com/DQmcj4DMQrHp54jDsgVo8FajaveCgiVZUhGYwNQFtCmLfQm/20180519_171529.gif)

**Comment by mcyusuf** [comment]
Hi, be sure to select a proper file for sending. WhatsApp has no support for sending folders. 
Try picking a document, music, picture file and use the share function, you'd see the difference.
Thanks.

**Comment by lfuelling** [comment]
As @mcyusuf says, it depends on what app you use for sharing. Some apps don't support sending files at all. 

The thing is that, as you can see at `io/lerk/lrkFM/util/ContextMenuUtil.java:160`, I use a mime type of `*/*` when sharing, to be more generic and let the app that receives the intent handle the typing (if neccessary). So only apps that support the sharing of "any" files will be able to properly share stuff.
