### ISSUE TITLE
Update generic error message to be less misleading when opening empty folders.

### ISSUE THREAD

**Issue by nicolaisueper** [lfuelling/lrkFM#33]
Beforehand: very nice app you've got there :)

I encountered a permission error after I created a new folder and cd'd into it. After creating another folder inside that folder, the error disappears and everything's hunky-dory.

I attached screenshots according to the error.

Greetz 
Nico

![screenshot_20181114-204232](https://user-images.githubusercontent.com/6556377/48508434-db59f900-e84e-11e8-9a42-f764fd2ccd60.png)
![screenshot_20181114-204940](https://user-images.githubusercontent.com/6556377/48508473-fa588b00-e84e-11e8-8ef7-6e7941233ece.png)
![screenshot_20181114-204948](https://user-images.githubusercontent.com/6556377/48508492-06dce380-e84f-11e8-9dde-00e76105a59f.png)
![screenshot_20181114-204954](https://user-images.githubusercontent.com/6556377/48508502-0c3a2e00-e84f-11e8-8d66-a7bd4518760e.png)

**Comment by lfuelling** [comment]
Hi, thanks for your bug report. 

The error message you are seeing is the generic access error message which also appears when opening empty folders. 

I'll try to add empty folders as a special case so the message is less misleading in this case.

**Comment by lfuelling** [comment]
(finally) fixed in cf722dc651252dd084f89822a689d2c292073844
