### ISSUE TITLE
attach APK to releases

### ISSUE THREAD

**Issue by IzzySoft** [lfuelling/lrkFM#8]
Could you please attach the `apk` file to your `releases/`, for folks outside Playstore? I'd then offer to take it into [my F-Droid compatible repo](https://apt.izzysoft.de/fdroid/repo).

Btw I just wonder: you write "ad free", and as far as I can see from the description there's no "network browsing". Correctly, the [Manifest](https://github.com/lfuelling/lrkFM/blob/master/app/src/main/AndroidManifest.xml) only shows request to read/write storage. Why then is it at Playstore it shows the app also wants: receive data from Internet, view network connections, full network access, prevent device from sleeping and read Google service configuration? Faulty evaluation on Google's end? I'm a bit confused.

**Comment by lfuelling** [comment]
Sorry but I will not put a signed apk on here as I only support the version hosted on GooglePlay. But there are already enough mirrors of lrkFM which don't require the PlayStore. For example semi-legit scraping sites like APKPure (https://apkpure.com/lrkfm-file-manager/io.lerk.lrkFM) provide the same file as is available on GooglePlay. Proof:

```
lerk@blackreach ~                                                                                                     [0:21:49]
>>>> shasum -a 512 Downloads/lrkFM\ File\ Manager_v1.6.2_apkpure.com.apk
84cfd82e0d111b2233370bcbdb8304a5dceb8c95bb6bd12fd5b782fa773ad37ec0c9a32d8a7a499820c315f452b78959922f9e92f05af0b308594212af543aed  Downloads/lrkFM File Manager_v1.6.2_apkpure.com.apk

lerk@blackreach ~                                                                                                     [0:21:59]
>>>> shasum -a 512 workspace/lrkFM/app/release/app-release.apk
84cfd82e0d111b2233370bcbdb8304a5dceb8c95bb6bd12fd5b782fa773ad37ec0c9a32d8a7a499820c315f452b78959922f9e92f05af0b308594212af543aed  workspace/lrkFM/app/release/app-release.apk
```

And last but not least you can always compile the app yourself if you want (and also remove all the google stuff from it).

---

I mean "Ad free" as in I do not show any ads in the application and do not collect any user data to sell (i.e. I don't earn anything with this). 
However I use Firebase Crashlytics which require internet access and which is a Google service. (The only data collected in this case is crash dump data coming from the application like file and line number where the crash happened and a Stacktrace)

More information on Crashlytics can be found here: https://firebase.google.com/docs/crashlytics/

I don't know where "prevent device from sleeping" comes from.

**Comment by lfuelling** [comment]
I tried it. A google-free version of this app can be created in about twelve minutes without coding assistance (just sublimetext and gradle).

You can use the `noogle` branch to build and put it in your repo if you want.

**Comment by IzzySoft** [comment]
Thanks for your fast response, @lfuelling ! Understood (and accept) the fact you don't want to provide the APK here – though I pity it. Admitted, there're sites like APKPure; but for the user that then means either to install manually (possibly missing updates), or have another app manager permanently running (or having to decide for one and miss other apps then) …

Not being a dev, and not having a development environment, I cannot compile myself unfortunately.

Special thanks for your explanations towards network, permissions and accessed data :+1: May I suggest to place them more prominently, e.g. in the main `README.md`? I won't be the only one curious :wink:

Finally: all the best for your good project!

**Comment by lfuelling** [comment]
Oh sorry, I thought that you could do that because you apparently also run a blog covering Android only. Also I read in the fdroid docs that apps that are submitted there will also be built from scratch.

Compiling the app is actually pretty easy (and all of the stuff is free obviously). You just need to download [AndroidStudio](https://developer.android.com/studio/) and the Android SDK (from within the preferences of android studio) and then just open the project using "`Open...`" and select "`Build > Generate Signed APK`" (where you'll need to create/open your android keystore which also is done in a fancy wizard)

Suggestion accepted 👍

**Comment by lfuelling** [comment]
@Poussinou sorry for randomly adding you to the conversation. I saw your PR where you talked about automatic releases to F-Droid when a commit is tagged. 

What do I have to do to activate that for this application=

**Comment by Poussinou** [comment]
This app is not in the official repo as far as I can see. Are you currently trying to write the metadata file to include your app in the F-Droid repo ("examples" [here](https://gitlab.com/fdroid/fdroiddata/tree/master/metadata), not all of them are in auto update mode)?

If this is the case, have a look [here](https://f-droid.org/docs/Build_Metadata_Reference/#Auto-Update-Mode). You just have to tag your releases properly, that's all, and you already do it :)

**Comment by IzzySoft** [comment]
@Poussinou the app is neither in Main nor in Archive.

@lfuelling nothing special, you already have tagged releases. But it would need to be added to the repo first (so you'd need to [file a request for packaging](https://gitlab.com/fdroid/rfp/issues/).

And no, I don't use Android Studio. And I won't in the near future. So if there's no APK attached to the releases, I cannot take it into my repo – thought that won't be needed if it's in the official repo :wink:

**Comment by IzzySoft** [comment]
:rofl: who was that with "first shoot then ask"? :rofl:

Happens. But while on it: what is your stance on this? Need help filing a RFP?

**Comment by lfuelling** [comment]
Han Solo 😋 

My stance: https://gitlab.com/fdroid/rfp/issues/755 :)

**Comment by IzzySoft** [comment]
> where does it fetch the author from when I don't specify it?

AFAIK it doesn't.

> is the thing I submitted okay as it is?

If the `sed` you just added removes the two unknown maven repos, I'd say yes. But that's up to a developer to decide – I cannot tell whether they might run into issues when building.

* How well does FDroid handle inconsistencies in terms of tags like 1.0, v1.1, v1.1.1, v1.2?

Never heard of any issues concerning that.

* Does this proposal automatically enable automatic builds or is there still a thing I need to do?

        AutoUpdateMode: Version v%v
        UpdateCheckMode: Tags

These two should take care for it – as long as you keep your tag format like that (i.e. `v<version>`).

* What about signing? Does FDroid use a global signing key or do I have to supply precompiled apk files?

AFAIK the signing key is app specific (per app Ciaran generates a signing key and then uses it only for that app – signing is still a manual step run on an "offline machine")

**Comment by IzzySoft** [comment]
Unfortunately you closed the RFP you've opened. May I return to start (without drawing 400 cash :smile:) and ask about the APK, so I could add your app to my repo?

**Comment by lfuelling** [comment]
My problem was: 
> Google does not publish the source code of pre-release Android Gradle plugin versions. So they're non-free software, which is not allowed by F-Droid's policy.

If you're okay with hosting non-free software I can try getting Travis to work properly (so it publishes the `.apk` to GitHub).

**Comment by IzzySoft** [comment]
Let's say I allow for some proprietary components not acceptable in the official repo. And if the reason you just gave is the only show-stopper for F-Droid, the app is perfectly acceptable for mine. If you're interested, my inclusion criteria can be [found here](https://gitlab.com/IzzyOnDroid/repo/) (and in the issue tracker there one can request apps to be included – plus of course report issues with the repo).

**Comment by IzzySoft** [comment]
Oh, I forgot to congratulate this issue to it's first birthday :rofl: Where do we stand now? I still cannot find the APK here.

**Comment by lfuelling** [comment]
Thanks for the reminder. 

I got it to work. Is the `.apk` enough or do you also need the `.json` file?

**Comment by IzzySoft** [comment]
Thanks! For my repo this is fully sufficient. Just added it, including the screenshots; should go live with the next sync (tomorrow evening UTC unless I trigger one manually).

According to my library scanner and a quick glance on the source, your app should be eligible for the official repo at [F-Droid](https://f-droid.org/) – which is more prestiguous than mine (though with mine, updates are faster). If you want your app there just let me know, and I gladly assist you (disclosure: I'm one of the maintainers there).

**Comment by lfuelling** [comment]
No thanks, as I might occasionally use beta software. As far as I understood it, they would block my app after I start using prerelease software again.

**Comment by IzzySoft** [comment]
Easy to deal with (btw: if I shall pick pre-release tags please let me know, I currently ignore them): As you tell the update checker what to look for, you could e.g. use `fdroid-%v` (or `v%v` as it is now) as pattern for the tag name – and simply use a different one for versions you don't want to be picked up, like `beta-1.2.3` for a versionName 1.2.3 F-Droid should ignore.

But as you wish; I gladly keep your app in my repo as well! I just triggered a sync now (there was another change requiring that), so your app should show up [here](https://apt.izzysoft.de/fdroid/index/apk/io.lerk.lrkFM) any moment now. Feel free to link there from the readme.

**Comment by lfuelling** [comment]
I'm closing this as the latest update appeared on FDroid just fine. 

Thanks again :)
